### ISSUE TITLE
Watch Mode and Real time editing no longer working on Gatsby Cloud

### ISSUE THREAD

**Issue by doigo** [sanity-io/gatsby-source-sanity#105]
Previewing on a bunch of our sites has started to play up on Gatsby Cloud CMS Previews. 

All running different versions of Gatsby and all work seamlessly locally has anyone had this issue ?

**Comment by daydream05** [comment]
Do you also have to refresh the page to see the changes? It could be hot reloading issue.

**Comment by doigo** [comment]
Seems like this was a gatsby cloud issue not the source plugin

**Comment by alvis** [comment]
@doigo how did you solve the issue in the end? I've the same problem.
