### ISSUE TITLE
Gatsby not using cdn APIs even when adding useCdn in gatsby-source-sanity plugin options

### ISSUE THREAD

**Issue by Turutupa** [sanity-io/gatsby-source-sanity#107]
Hi!

Perhaps this is a misunderstanding of some sort from side as I am new to Sanity. Nonetheless, I added the _useCdn_ parameter in _gatsby-config.js_ under the _gatsby-source-sanity_ plugin options as such

```
...
{
      resolve: "gatsby-source-sanity",
      options: {
        ...clientConfig.sanity,
        token,
        useCdn: true,   // <- here
        watchMode: !isProd,
        overlayDrafts: !isProd && token
      }
    }
...
```

But in my Sanity project I see **API CDN Requests 0 of 500k** and 24h have gone by (in case it wasn't updating)

Is there anything else I have to modify besides adding _useCdn_ for it to work? Thanks in advance

**Comment by stiwwelll** [comment]
Hey @Turutupa ,

I think it has to do with the [Sanity Cache Policy](https://www.sanity.io/docs/api-cdn#01e959b47cfb), especially this point:

```
Requests with Authorization headers are rejected, i.e. authenticated requests
```

By adding the auth token, you basically get the response from the regular, uncached API. Make sure to remove the token and set your dataset to public. I hope this helps.

**Comment by rexxars** [comment]
This plugin will never actually use the API CDN, since it relies on the export endpoint and not the query endpoint. Having said that, it uses 2 API requests per build (one for the GraphQL schema, one for the export), so I don't think this is something you should worry about :)

**Comment by Turutupa** [comment]
Hi Rexxars!

Thanks for your response. As I mentioned, I am new working with Sanity. Could you clarify/elaborate a bit more on what you mean by "one api request (...) for the export"?

Basically you're saying... I should not be worried as each time a user hops in the website _only_ 2 requests will be performed right? That's neat :)
