### ISSUE TITLE
getFluidGatsbyImage is not a function

### ISSUE THREAD

**Issue by alexanderfountain** [sanity-io/gatsby-source-sanity#112]
Does anyone have getFluidGatsbyImage working with Gatsby v3?

Trying to get rich text block images working with gatsby image, but getting error 
Uncaught TypeError: (0 , gatsby_source_sanity__WEBPACK_IMPORTED_MODULE_4__.getFluidGatsbyImage) is not a function

"gatsby": "^3.1.1",
"gatsby-source-sanity": "^7.0.0",
"@sanity/block-content-to-react": "^2.0.7",

Any help much appreciated.

**Comment by sergiobarria** [comment]
From what I understand Fluid doesn't work anymore with Gatsby V3. 
I manage to render rich text images adding in my serializers the MainImage component  from `gatsby-plugin-image`. Also to query the image I used graphQL and added `gatsbyImageData` from `gatsby-source-sanity`. 

Here my serializer option
`
mainImage: props => (
      <MainImage src={props.node.asset.url} alt={props.node.alt} />
    ),
`

Hope this can help

**Comment by rexxars** [comment]
@sergiobarria is right, the fixed/fluid approach has been removed in favor of the new gatsby-plugin-image included in gatsby v3.

There is a migration guide linked in the readme which might help: https://github.com/sanity-io/gatsby-source-sanity/blob/main/MIGRATION.md

**Comment by alexanderfountain** [comment]
Ahh of course. That solved it for me. Thanks!
