### ISSUE TITLE
Bring back gatsbyImageData node extension

### ISSUE THREAD

**Issue by aaronadamsCA** [sanity-io/gatsby-source-sanity#113]
I could do this using v7.0.0 of this plugin:

```js
import { GatsbyImage } from "gatsby-plugin-image";

export const Person = ({ data }) => (
  <article>
    <h2>{data.sanityPerson.name}</h2>
    <GatsbyImage image={data.sanityPerson.profileImage.asset.gatsbyImageData} />
  </article>
);

export const query = graphql`
  query PersonQuery {
    sanityPerson {
      name
      profileImage {
        asset {
          gatsbyImageData(layout: FULL_WIDTH, aspectRatio: 3)
        }
      }
    }
  }
`;
```

This is _much_ better syntax than what's recommended in the current README, and [a much better fit with Gatsby and `gatsby-plugin-image`](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/#dynamic-images). I already provided my Sanity config to your plugin in my `gatsby-config.js`; there's no reason I should need to provide it again every time I want to render an image!

This is no longer working due to the removal of [extendImageNode.ts](https://github.com/sanity-io/gatsby-source-sanity/blob/v7.0.0/src/images/extendImageNode.ts) in v7.0.1.

Please restore this functionality and bring back this much easier way of working with Sanity images in Gatsby. 💪

**Comment by ehowey** [comment]
I just wanted to pop in here to echo that this did seem like a simpler API to me as well. I was getting some weird black "ghosting" around transparent png images however that is resolved now that I switched to the `getGatsbyImageData` function however so I wonder if there was a reason they removed this GraphQL field?

**Comment by drskigen** [comment]
Agreed. Is there any advantage to the new method? The `7.0.0` method seemed much cleaner and easier to use

**Comment by bjoerge** [comment]
Fixed in v7.0.3

**Comment by nickspaargaren** [comment]
Works like a charm, thanks a lot!

**Comment by aaronadamsCA** [comment]
Great stuff, thanks @bjoerge.

(FYI there's still a leftover `import {getGatsbyImageData} from 'gatsby-source-sanity'` left in the README.md example.)

**Comment by bjoerge** [comment]
Well spotted @aaronadamsCA! Fixed now, thanks 👍
