### ISSUE TITLE
'Error: Schema must contain uniquely named types but contains multiple types named "GatsbyImageLayout"

### ISSUE THREAD

**Issue by 3200pro** [sanity-io/gatsby-source-sanity#122]
Hi Sanity,

Ran into this error today while using gatsby-source-shopify and gatsby-source-sanity at the same time: 

```
Missing onError handler for invocation 'building-schema', error was 'Error: Schema must contain uniquely named types but
contains multiple types named "GatsbyImageLayout".'.
```
Removing either the shopify or sanity plugin from gatsby-config removes the error. I looked for a solution for a while and here's a similar scenario that happened while someone was using the contentful plugin alongside the shopify plugin:

**Problem the had:**  _Development build fails if I have both gatsby-source-contentful and gatsby-source-shopify-experimental enabled but succeeds if I drop either from gatsby-config.js._ 
 
**Gatsby's Answer:**  _The problem arises when two different source plugins are using gatsby-plugin-image_

**Their Solution:** _This is actually a bug in gatsby-source-contentful, rather than this plugin. I've opened a PR which should fix it._

**Source:**
[https://github.com/gatsbyjs/gatsby-source-shopify/issues/65](https://github.com/gatsbyjs/gatsby-source-shopify/issues/65)

**PR he mentioned**
https://github.com/gatsbyjs/gatsby/pull/30834

**Comment by alainkaiser** [comment]
Hi sanity, hi @3200pro 

I have the exact same issue and created a bug at "gatsby-source-shopify" but i am not sure which plugin is the source of the error.

Also noticed the already created issues at "gatsby-source-shopify" which @3200pro mentioned.

My bug description:

https://github.com/gatsbyjs/gatsby-source-shopify/issues/137

Would be helpful if we could resolve this issue together as i am stuck at the moment.

Thanks in advance for the help!

**Comment by 3200pro** [comment]
@alainkaiser ,

Based on the [PR](gatsbyjs/gatsby#30834) at contentful, my guess is that it's a Sanity issue that needs to be corrected.

**Comment by alainkaiser** [comment]
Any new on this one? @3200pro Did you manage to get it work somehow (workaround)?

**Comment by geoffreyjball** [comment]
Setting `options.downloadImages: true` in the gatsby-source-shopify configuration seems to permit the build, though it definitely remains a workaround and not a solution.

**Comment by tizzle** [comment]
Hi, is this being worked on? I think this is quite important to fix, as the workaround from @geoffreyjball works, but is not good for builds on e.g. Netlify which are time-constrained on free tiers. Downloading the images bloats the build process unnecessarily imho.

Best regards

**Comment by SimeonGriggs** [comment]
I've just resolved this same issue by:

1. Installing `gatsby-plugin-image` (even if you don't use it)
2. Adding `gatsby-plugin-image` to `plugins` in `gatsby-config.js`

**Comment by Jxmedia** [comment]
> I've just resolved this by:
> 
> 1. Installing `gatsby-plugin-image` (even if you don't use it)
> 2. Adding `gatsby-plugin-image` to `plugins` in `gatsby-config.js`

This worked for me as expected
