### ISSUE TITLE
Build delta change computation does not scale to large datasets

### ISSUE THREAD

**Issue by atombender** [sanity-io/gatsby-source-sanity#149]
The [current delta logic](https://github.com/sanity-io/gatsby-source-sanity/blob/main/src/gatsby-node.ts#L255-L257) relies on getting all of the IDs from a dataset first. However, with large datasets, this can take a very long time, and might even time out, as the query in question loads all the IDs in one go:

```groq
*[!(_type match "system.**")]._id
```

This will effectively cause all IDs to be loaded and rendered into JSON before it is returned to the client.

A more incremental approach is needed to avoid running into this issue, where the IDs are paginated:

```groq
*[!(_type match "system.**") && id > $prevId][0..1000]._id
```

For each page, `prevId` can be filled in with the highest ID encountered. This is much faster, and avoids running into timeouts.

An even better approach would be to only fetch anything with `_updatedAt > $lastBuildTime`, though this does not solve how to sync deleted documents. But it's possible that the history API could be used for this.

There are other aspects of this logic that could be optimized for large datasets. For example, `documentIds.includes()` is called for every single document, which is a linear search that's going to be very slow if the document ID list contains thousands of documents. Instead, the IDs should be indexed into an efficient set first for fast lookup.

**Comment by AbdallahAbis** [comment]
@atombender Also, the `documentIds` variable should be a `Map` because `documentIds` could have 300K ids inside and checking `documentIds.includes` means checking 300K ids against 300K nodes on Gatsby cache, `O(n)^2` maybe.

**Comment by AbdallahAbis** [comment]
Also, the usage of the store helper to save the last build time is not a good practice.
From [Gatsby's docs](https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#store) 

> store :
Internal redux state used for application state. Do not use, unless you absolutely must. Store is considered a private API and can change with any version.
