### ISSUE TITLE
GraphQL query not displaying data

### ISSUE THREAD

**Issue by MaralS** [sanity-io/gatsby-source-sanity#159]
Hello,

I'm currently developing my website using gatsby and sanity but I have issues displaying the data on the front end. 

I created a document in sanity to reuse the info about the company. When I check on the graphQL server I have the information but when I try to show the data on a component, it remains blank.

I really don't know what to do, I don't know what I'm doing wrong because I followed the documentation.

Maybe someone could help me to see my error.

![image](https://user-images.githubusercontent.com/19915917/176232962-493939b5-02a3-4a13-bad5-a0a9674a469e.png)
My query works on the graphql interface

My code 
```

components/companyInfo.js

import React from "react"
import { useStaticQuery, graphql } from "gatsby"

export default function CompanyInfo() {
  const data = useStaticQuery(graphql`
    query CompanyInfo {
      allSanityCompanyInfo {
        nodes {
          id
          zipCode
          name
          city
          companyType
          email
          address
          naf
          siret
          phoneNumber
        }
      }
    }
  `)
  return (
    <div>
      <p>{data.allSanityCompanyInfo.nodes.id}</p>
      <p>{data.allSanityCompanyInfo.nodes.companyType} {data.allSanityCompanyInfo.nodes.name}</p>
    </div>
  )
}
```

```
pages/index.js

import * as React from "react"
//import { Link } from "gatsby"
//import { StaticImage } from "gatsby-plugin-image"

import Layout from "../components/layout"
import Seo from "../components/seo"
//import * as styles from "../components/index.module.css"
import CompanyInfo from "../components/companyInfo"

const IndexPage = () => (
  <Layout>
    <Seo title="Home" />

    <CompanyInfo/>



  </Layout>
)

export default IndexPage
```

![image](https://user-images.githubusercontent.com/19915917/176233379-b6af77f9-110a-4506-96db-29a8c3745de1.png)

**Comment by raae** [comment]
A query for allSanityCompanyInfo returns an array of nodes, either change your code to use the first node (and only node returned):

```
<p>{data.allSanityCompanyInfo.nodes[0].id}</p>
```

Or you can change the query to ask for only one node using `sanityCompanyInfo` and change the above code to:

```
<p>{data.sanityCompanyInfo.id}</p>
```
