### ISSUE TITLE
Can't get GatsbyImageData from Image in Block element

### ISSUE THREAD

**Issue by ecupaio** [sanity-io/gatsby-source-sanity#174]
I have an FAQ component with a repeatable array of questions and answers. The answers require rich text so I created an array with a type of block and image like so: 
```
export default {
  name: 'faqItem',
  title: 'FAQ Item',
  type: 'object',
  fields: [
    {
      title: 'Question',
      name: 'q',
      type: 'string'
    },
    
    {
      title: 'Answer',
      name: 'a',
      type: 'array',
      of: [ 
        {type: 'block'},
        {type: 'image'}
      ]
    }
  ]
}
```
I ran the following static query in my playground: 
```
query FAQ {
  sanityFaq {
    title
    list {
      q
      _rawA
    }
  }
}
```
_rawA gets my all the rich text: normal, headings, lists, and links with the proper values for each, but image outputs the following: 
```
{
  "_key": "183fcbdcd3f5",
  "_type": "image",
  "asset": {
    "_ref": "image-4b6600a50705e57a7d2a56924cbe7500420ed936-1450x1411-png",
    "_type": "reference"
  }
}
```
The gatsby image plugin needs the GatsbyImageData object to function properly so I wasn't sure what to do with that ref since there's not even a domain to fix it to. 

[This developer](https://github.com/ShaifArfan), @SharifArfan, [found a complex workaround](https://youtu.be/6OCji3Eyib4?t=1481) to make it work and I dutifully copied their code, but the bottom line is this plugin should properly source assets regardless of content type if you're going to charge $99/month.

**Comment by kmelve** [comment]
Hi! 

I agree that it would be nice if it were simpler. But have you tried this approach from the [plugin documentation](https://github.com/sanity-io/gatsby-source-sanity#using-images-outside-of-graphql)? I believe it would look something like this inside of the Portable Text components object: 

```jsx
import {GatsbyImage} from 'gatsby-plugin-image'
import {getGatsbyImageData} from 'gatsby-source-sanity'

const sanityConfig = { 
  projectId: "9qw2u5yr",
  dataset: "production",
}; // or import it from a file that exports the config object

export const portableTextComponents = {
  types: {
    image: ({ value }) => {
      const imageData = getGatsbyImageData(value?.asset?._ref, { width: 1024 }, sanityConfig);
      return <GatsbyImage image={imageData} />;
    },
  },
};
```

**Comment by ecupaio** [comment]
Thanks @kmelve for pointing me in the right direction. I feel like a dummy not finding that earlier. I was looking in the Portable Text docs and trying to wrap my head around all the concepts. Plus I watched [your explainer](https://www.sanity.io/guides/introduction-to-portable-text) on Portable Text, but you use a deprecated plugin, which further compounded my confusion. 

This seems like a much cleaner way to write it so I'll try it out that way. For my understanding, what are those question marks doing in the object data or do they just indicate you're using placeholder?

**Comment by kmelve** [comment]
Aha, I see. I'm using https://github.com/portabletext/react-portabletext in the example over. The question marks are for [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), in other words, if the `value` or `asset` properties for some reason is `undefined` or falsish, then the code won't break with the "can't access property on undefined" error.

**Comment by ecupaio** [comment]
@kmelve thanks for that! I'm a react noob if you can't tell already. I'll add it to my running "weird react stuff" doc

**Comment by kmelve** [comment]
No worries – we have all been there! Btw, do join our [community](https://slack.sanity.io) if you haven't already. We can help out there too – also with React stuff 🙌

**Comment by ecupaio** [comment]
[It's working!](https://media0.giphy.com/media/CuMiNoTRz2bYc/giphy.gif?cid=ecf05e4792k7rsfu6ob7hi0tnxqbv8qa5wtt6hwx0xkewdbv&rid=giphy.gif&ct=g) Much simpler implementation. I was a bit confused about the wording "Using images outside of GraphQL" since I'm using GraphQL to get the images, but I see now it means getting the GatsbyImageData takes some outside processing with the getGatsbyImageData function from the gatsby-source-sanity .

**Comment by ecupaio** [comment]
@kmelve I have indeed. Thanks again for being patient and understand unlike a certain online help forum where the nerd rage overflows.
