### ISSUE TITLE
Planned support for Gatsby 5?

### ISSUE THREAD

**Issue by LiamWinterton** [sanity-io/gatsby-source-sanity#192]
Just looking for an update on this, as we're looking to adopt soon and would love to start on Gatsby v5 from the get go :)

**Comment by BradNut** [comment]
Same question given trying to `npm install` with all the latest Gatsby 5 dependencies leads to the following peer dependency issue.

`
npm install     
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project
npm ERR! Found: gatsby@5.0.1
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0 || ^4.0.0" from gatsby-source-sanity@7.5.1
npm ERR! node_modules/gatsby-source-sanity
npm ERR!   gatsby-source-sanity@"^7.5.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`

**Comment by chrispecoraro** [comment]
Same question for @rexxars. 
build succeeds with warning:
`warn Plugin gatsby-source-sanity is not compatible with your gatsby version 5.0.1 - It requires gatsby@^3.0.0 || ^4.0.0
`

**Comment by BradNut** [comment]
@chrispecoraro For me the build only succeeds if I install with `--legacy-peer-deps` otherwise I'm getting a hard fail like above. 

Hopefully @rexxars can comment? :)

**Comment by ptpittman** [comment]
Same here. Am I right in understanding that --legacy-peer-deps would just _not_ install the older version gatsby peer dep? Which I presume means it'll just run headlong into any breaking changes in v5, but there don't seem to be too many to be overly worried about...
