### ISSUE TITLE
Error building gatsby after updating to 7.7.0

### ISSUE THREAD

**Issue by frodestorhaug** [sanity-io/gatsby-source-sanity#245]
ERROR #85901  GRAPHQL.UNKNOWN

There was an error in your GraphQL query:

Cannot read properties of undefined (reading 'type')

works on 7.6.3 - Is this a change or a bug ?

**Comment by djavco** [comment]
I'm also seeing error having updated to 7.7.0 with empty fields in reference objects - I've had to downgrade to earlier version

**Comment by fvieira** [comment]
We are seeing a similar bug too, also had to downgrade.

**Comment by dmorda** [comment]
Same here, moving back to 7.6.3 fixed it for me.

**Comment by chrispecoraro** [comment]
There are not enough tests to cover such drastic changes and obviously, the question is always "Which side should maintain this plugin, now: Gatsby/Netlify or Sanity?"

**Comment by chrispecoraro** [comment]
@ascorbic A colleague mentioned that it looks like `.type` is being used instead of `._type`.

**Comment by ascorbic** [comment]
Can those of you who are having these issue share the specific queries that are causing the problem, and if possible the relevant parts of the schema? I've not been able to reproduce this myself, but this may just be that my schema does't include the particular types that cause this. You'll find the schema in `.cache/schema.gql` after you do a build

**Comment by ascorbic** [comment]
Thanks

**Comment by dmorda** [comment]
Let me know if the attached helps.
[schema.txt](https://github.com/sanity-io/gatsby-source-sanity/files/12114307/schema.txt)
[bulid log.txt](https://github.com/sanity-io/gatsby-source-sanity/files/12114308/bulid.log.txt)

**Comment by JustFly1984** [comment]
reverting it to 7.6.3 fixed it for me too.

**Comment by ascorbic** [comment]
If anyone else is able to share the error (with query) and `.cache/schema.gql` it would be a great help. Thanks

**Comment by ascorbic** [comment]
@dmorda is the schema you shared from the same plugin version as the one that was erroring? Also, can you let me know which version of gatsby that you're using?

**Comment by dmorda** [comment]
Sorry, I forgot to include those details. The files I attached were from the build that is failing. Specifically, I upgraded gatsby-source-sanity from 7.6.3 (working) to 7.8.0 (not working). When I ran the build that is failing, I was using gatsby@5.11.0. I'm on macOS Apple Silicon using Node 18.17.0.
