### ISSUE TITLE
Gatsby build fails because of incompatible gatsby or gatsby-source-sanity version

### ISSUE THREAD

**Issue by andersnylund** [sanity-io/gatsby-source-sanity#26]
I am running gatsby and sanity together. The structure of the project was constructed following [this tutorial](https://www.sanity.io/blog/how-to-quickly-set-up-a-gatsby-js-jamstack-website-with-a-headless-cms). 

Now, the problem is that when I run the gatsby project, I get the following error:  

`You are running a version of Gatsby that is not supported by gatsby-source-sanity. Please downgrade to gatsby <= 2.1.22 or upgrade gatsby-source-sanity to >= 2.0.0`.

My current dependencies are

```json
"dependencies": {
    "@sanity/block-content-to-react": "^2.0.6",
    "@sanity/image-url": "^0.140.0",
    "date-fns": "^1.30.1",
    "dotenv": "^6.2.0",
    "gatsby": "^2.0.76",
    "gatsby-plugin-postcss": "^2.0.2",
    "gatsby-plugin-react-helmet": "^3.0.2",
    "gatsby-source-sanity": "^1.0.3",
    "postcss-import": "^12.0.1",
    "postcss-preset-env": "^6.5.0",
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
    "react-helmet": "^5.2.0",
    "typeface-lato": "^0.0.54"
  },
```

Is it intentional that previously working build are now failing because of this?

**Comment by andersnylund** [comment]
I tried upgrading both gatsby and gatsby-source-sanity to their most recent versions `gatsby 2.4.2` and `gatsby-source-sanity 4.0.1`. However, now I get the following error: `error GraphQL Error Encountered 1 error(s): Unknown field 'allSanityMainImage' on type 'Query'.`

**Comment by rexxars** [comment]
Where does the `allSanityMainImage` query come from?
This isn't valid anymore, because it's not a document but an inline object (embedded within a document somewhere)

**Comment by rexxars** [comment]
Closing this. 2.x to 4.x includes two breaking changes which also affects queries. Unfortunately, that means queries will have to be rewritten sometimes.
