### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by RobAWilkinson** [sanity-io/gatsby-source-sanity#27]
Is there a way to track changes that are made/improved with new releases? I'm currently using 1.0.4 but would love to know what improvements have been made?

**Comment by RobAWilkinson** [comment]
There is a changelog, but its not connected to release notes

**Comment by rexxars** [comment]
Our intention is for the changelog to include most changes. I'm not sure what you mean by "not connected to release notes" - are you thinking of github releases, or something else?

**Comment by RobAWilkinson** [comment]
@rexxars thats correct, was thinking of official release notes on github releases

**Comment by kmelve** [comment]
We'll consider this, but I'm closing this for now. Thanks for the suggestion!
