### ISSUE TITLE
Add support for inferred width with getFixedGatsbyImage

### ISSUE THREAD

**Issue by piersolenski** [sanity-io/gatsby-source-sanity#28]
Currently if you don't specify a width for `getFixedGatsbyImage` it falls back to the default value `exports.DEFAULT_FIXED_WIDTH`. It would be great if you could omit this when specifying a height in the same way that you can when using graphql. For example the following query only specifies a height and the width is then inferred from the image dimensions.

```
file(relativePath: { eq: "images/logo.png" }) {
  childImageSharp {
    fixed(height: 24) {
      ...GatsbyImageSharpFixed
    }
  }
}
```

**Comment by roffelsaurus** [comment]
check the readme again. The reason for the naming(«fixed») becomes apparent when you see it’s cousin Fluid which solves your use case.

**Comment by rexxars** [comment]
Fixed/fluid has been deprecated in favor of the new [gatsby-plugin-image](https://github.com/sanity-io/gatsby-source-sanity/blob/main/MIGRATION.md)
