### ISSUE TITLE
Issue with formatString on dates.

### ISSUE THREAD

**Issue by danielvanc** [sanity-io/gatsby-source-sanity#30]
Raising this issue after a chat with @rexxars. https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1559683107038900. Be great to have formatString back for working with dates now that Gatsby has released a new version that will allow gatsby-source-sanity to use formatString again, as my project uses it allot. 👍 

Any info you need, please let me know :)

**Comment by rexxars** [comment]
Fixed by 851a194f2d39505849e6dd029ff101e3e06362c8 and released as v4.0.3. Requires gatsby >= 2.5.0 to work. Thanks for pushing me to do this :)

**Comment by danielvanc** [comment]
Working great my end now - thanks so much @rexxars 👍
