### ISSUE TITLE
Add <link preconnect> for Sanity image API

### ISSUE THREAD

**Issue by KyleAMathews** [sanity-io/gatsby-source-sanity#35]
I was doing some [profiling for the new themejam site](https://github.com/gatsbyjs/themejam.gatsbyjs.org/issues/17) and noticed that loading the first image from Sanity's image API takes some time due to needing to connect to a new domain.

It'd speed things up a lot if sites using gatsby-source-sanity add `<link href="https://cdn.sanity.io/" rel="preconnect" crossorigin>`. It then occurred to me that this plugin could just do that for each site in `gatsby-ssr.js` :-)

**Comment by rexxars** [comment]
That's a good idea, Kyle! Will see if I can implement that.

**Comment by rexxars** [comment]
Added in 5.0.1! Thanks!
