### ISSUE TITLE
Ability to Incorporate Images In Build's Static Assets

### ISSUE THREAD

**Issue by zprobst** [sanity-io/gatsby-source-sanity#40]
Instead of having image assets being served from `cdn.sanity.io`, is there an approach for the used image assets to be downloaded ad added to a production build? We would prefer to use our own CDN for caching assets.

**Comment by kmelve** [comment]
Hi! You can now use [this transformer plugin](https://github.com/reactgraphqlacademy/gatsby-source-sanity-transform-images) to achieve this functionality. I'm therefore closing this issue.
