### ISSUE TITLE
Throttle watchMode

### ISSUE THREAD

**Issue by frodehansen2** [sanity-io/gatsby-source-sanity#48]
Is there some way to not have the watchMode trigger on every keyChange, but maybe on every page reload? As it is now, it triggers a huge amount of api-calls to sanity, which is not always a good thing.

**Comment by frodehansen2** [comment]
Got answers through slack

**Comment by igorkoho** [comment]
Care to pass the answer along?

**Comment by JugglerX** [comment]
Also having this issue

**Comment by rexxars** [comment]
Gatsby shouldn't trigger any more API calls to Sanity. It only fetches the data on start, and merges data from the watch mode listener. That's 2 API calls per `gatsby develop`. Could you elaborate on where you're seeing these API calls? Are you running client-side GROQ-requests on mount, by any chance?

**Comment by igorkoho** [comment]
@rexxars I'm just testing out sanity right now, and i've done perhaps several `gatsby develop`s, yet the sanity dashboard says i've used 2k api calls :/

**Comment by rexxars** [comment]
@igorkoho The studio also uses API calls quite aggressively. Data imports as well. It's hard to say without having a look at your specific case though. If you join our [Slack](https://slack.sanity.io/) we may be able to help you.

**Comment by frodehansen2** [comment]
When i mentioned this on slack, Knut, at Sanity, guessed our high api count was because of a bug in sanity studio, and not related to the gatsby-source-sanity plugin.
