### ISSUE TITLE
Resolving references

### ISSUE THREAD

**Issue by miracle2k** [sanity-io/gatsby-source-sanity#5]
So I have a reference in Gatsby from one type to another. Is there currently a way to model this in GraphQL using two node types?

I have a 

```
     type: 'array',
      of: [
        // Which this would allow inline-adding of items
        {type: 'reference', to: {type: 'callToAction'}},
      ],
```

 By default, I only get the fields `_key, _ref_, _type`. I know I can change the GROQ query to pull in the relationship fields directly, but I'd like it point to the `sanityCallToAction` node instead.

**Comment by rexxars** [comment]
Not in the current version, as far as I know, but we are working on a new version where every document is a Gatsby node, and references are automatically handled for you. Can't give you an exact ETA, but it isn't too far of.

**Comment by miracle2k** [comment]
Sounds good! I just want to mention a similar situation I ran into, where I have references inside an array of blocks, i.e.:

```js
{
      title: 'Text',
      name: 'text',
      type: 'array',
      of: [
        {
          type: 'block',
        },
        {type: 'reference', to: {type: 'keyPoint'}},
      ]
    }
```

So this then gives me:

By default this just gives me:

```js
{
"_key": ...
"_ref": ...
"_type": "reference"
}
```

So I changed by query to:

```
"text_asString": text[]{
   ...,
   "resolved": @->
},
```

Which works, but has the downside, in Gatsby, of always pulling in the full referenced object, which can be both a performance concern and a data exposure issue.

I imagine that GraphQL subtypes could maybe help here, as in:

```
blockContentfield {
       ... as CrewMember {
         name
       }
    }
}
```

**Comment by rexxars** [comment]
This is a v0 issue, closing

**Comment by Manicbsm27** [comment]
All documents are greater than given value
  """
  _updatedAt_gt: DateTime
  """
  All documents are greater than or equal to given value
  """
  _updatedAt_gte: DateTime
  """
  All documents that are equal to given value
  """
  _rev: String
  """
  All documents that are not equal to given value
  """
  _rev_not: String
  """
  All documents contain (match) the given word/words
  """
  _rev_matches: String
  _rev_in: [String!]
  _rev_not_in: [String!]
  """
  All documents that are equal to given value
  """
  _key: String
  """
  All documents that are not equal to given value
  """
  _key_not: String
  """
  All documents contain (match) the given word/words
  """
  _key_matches: String
  _key_in: [String!]
  _key_not_in: [String!]
  """
  All documents that are equal to given value
  """
  title: String
  """
  All documents that are not equal to given value
  """
  title_not: String
  """
  All documents contain (match) the given word/words
  """
  title_matches: String
  title_in: [String!]
  title_not_in: [String!]
  """
  All documents that are equal to given value
  """
  description: String
  """
  All documents that are not equal to given value
  """
  description_not: String
  """
  All documents contain (match) the given word/words
  """
  description_matches: String
  description_in: [String!]
  description_not_in: [String!]
  """
  All documents that are drafts
  """
  is_draft: Boolean
}

type YoutubeVideo {
  _key: String
  _type: String
  url: String
}
