### ISSUE TITLE
How do I output block content

### ISSUE THREAD

**Issue by wispyco** [sanity-io/gatsby-source-sanity#51]
I see that there are two different references to my block content field, one is `_rawProjectDesc` and the other is just `projectDesc` The query I am playing with in graphiQL looks like this. Which am I supposed to use to get the block content, `projectDesc.sanityChildren.text` or the `_rawProjectDesc` only the raw is outputting data right now. And if someone could point me in the direction of once I get the whole block content how to use this https://www.npmjs.com/package/@sanity/block-content-to-react

Thanks ahead of time.

```
query MyQuery {
  allSanityBlogPost {
    edges {
      node {
        scopeMainTitle
        projectDesc {
          _key
          _type
          style
          list
          sanityChildren {
            _key
            _type
            text
          }
        }
        scopes {
          _key
          _type
          scopeValue
        }
        _rawProjectDesc(resolveReferences: {maxDepth: 10})
      }
    }
  }
}
```

Update:

I seem to have gotten something working with the serializer, is this the recommended way to do things, grab the raw field?

`<BlockContent blocks={post._rawProjectDesc} serializers={serializers} />`

**Comment by roffelsaurus** [comment]
yes that is the way. it’s documented in the readme
