### ISSUE TITLE
Images are getting cropped unexpectedly

### ISSUE THREAD

**Issue by axelekwall** [sanity-io/gatsby-source-sanity#59]
I’m working on integrating a Gatsby site with Sanity. I previously had all data as local files (markdown/images) and the images were loaded with `gatsby-image-sharp`. The change to fetch the content from Sanity with the `gatsby-source-sanity` plugin has been mostly smooth but with one major issue. When querying images with a fixed `height` or fluid `maxHeight` the images is returned cropped. I want the original aspect ratio but with the images scaled to the desired height and I had this working with the old setup with local images.

An example of what the relevant part of a query looked like before:

```graphql
image {
	childImageSharp {
		fixed(height: 140) {
			…GatsbyImageSharpFixed
		}
	}
}
```

And now with Sanity to:
```graphql
image {
	asset {
		fixed(height: 140) {
			…GatsbySanityImageFixed
		}
	}
}
```

What I found when digging a bit deeper was that this plugin adds `&fit=crop` to the image url from sanity cdn. If I manually remove this url-parameter in the dev tools I get the image I want that is the original aspect ratio and 140px in height in this example.

Based on a discussion in the Sanity slack this does not seem to be expected behavior. Maybe this can be solved by adding a `crop` boolean parameter to the graphql schema to make the cropping optional?

**Comment by MantasMikal** [comment]
I have the same issue

**Comment by daydream05** [comment]
Same issue here! When I try to add maxWidth bigger than the 1000, it crops it.

**Comment by daydream05** [comment]
So I think I figured it out.

So `&fit=crop` is the default settings and it should work as intended for most cases since we're providing height and width.

But what it wouldn't do is scale your image up.

So the problem happens when you try to  query a maxWidth or maxHeight larger than your image's maximum dimension. It's not gonna scale it up, what it will do is return the actual image itself.

```
mainImage {
        asset {
          _id
          fluid(maxHeight: 3000, maxWidth: 6000) {
            ...GatsbySanityImageFluid_noBase64
          }
        }
        alt
      }
```

**Comment by rexxars** [comment]
Fixed/fluid has been deprecated in favor of the new [gatsby-plugin-image](https://github.com/sanity-io/gatsby-source-sanity/blob/main/MIGRATION.md)
