### ISSUE TITLE
Feature request: ability to pass image transformation parameters with getFluidGatsbyImage and getFixedGatsbyImage

### ISSUE THREAD

**Issue by blimpmason** [sanity-io/gatsby-source-sanity#62]

**Comment by jaybowles** [comment]
Adding my support for this.

**Comment by blimpmason** [comment]
Honestly it would be great to have access to all image transformation url parameters: 
https://www.sanity.io/docs/image-urls#the-url-parameters-BhPyF4m0

**Comment by rexxars** [comment]
Fixed/fluid has been deprecated in favor of the new [gatsby-plugin-image](https://github.com/sanity-io/gatsby-source-sanity/blob/main/MIGRATION.md).

Would be willing to take a pull request based on the new plugin which does not touch sizing or cropping related parameters, as these are somewhat complicated.
