### ISSUE TITLE
getFixedGatsbyImage base64 null

### ISSUE THREAD

**Issue by LeonSkrilec** [sanity-io/gatsby-source-sanity#64]
Hey!

Is `getFixedGatsbyImage()` method capable of returning base64 image previews? Currently I am using it to fetch fixed images to display them using `gatsby-image`, but base64 property is always null.

Do I have to enable previews somewhere?

Response preview:

`
{base64: null,
aspectRatio: 1.7,
width: 1200,
height: 675,
src: "https://cdn.sanity.io/images/oslxrhwr/production/4af65ae375e4d12b2f1914e9f006294144fc398f-2560x1440.jpg?w=1200&h=675&fit=crop",
...
}
`

Thanks for the help!

Leon

**Comment by blimpmason** [comment]
@LeonSkrilec what does your query look like?

I've noticed that when using `getFluidGatsbyImage` and `getFixedGatsbyImage` methods (outside of graphql) you have to pass the full asset object rather than asset id in order to get the base64 string. I think this might be a bug actually.

**Comment by LeonSkrilec** [comment]
Yeah I resolved the issue through Sanity #help slack channel. 

There are two extra things required to get the low quality preview, which are not mentioned in documentation:
1. You have to return "lqip" field from your sanity image schema object like this
`name: "image",
  type: "image",
  options: {
    metadata: ["lqip"]
  },
  fields: []
}`
2. As you said, you have to pass the whole image asset object (with "lqip" property) to `getFixedGatsbyImage` or `getFluidGatsbyImage`.

I think it would be helpful if this was mentioned in documentation.

**Comment by tunztunztunz** [comment]
@LeonSkrilec I know this issue is pretty old, but could you share the query? I don't understand how to return the "lqip" field from my schema object if I'm using `getFluidGatsbyImage`. I think your solution could save me right now.

**Comment by LeonSkrilec** [comment]
You define your image in your schema like this:
`{
    name: "coverImage",
    title: "Cover image",
    type: "image",
    options: { metadata: ["lqip"] },
}`

And your GraphQL query:
`
coverImage {
    asset {
        _id
        fluid(maxWidth: 2800) {
        ...GatsbySanityImageFluid_noBase64
        }
        metadata {
        lqip
        }
    }
}
`

**Comment by tunztunztunz** [comment]
I see what you mean now. Thanks for getting back @LeonSkrilec I appreciate it.
