### ISSUE TITLE
[6.0.0-beta.0] markDefs not available on GraphQL

### ISSUE THREAD

**Issue by fvieira** [sanity-io/gatsby-source-sanity#67]
I was testing the new version today which fixes the terribly annoying nested blocks bug (and thank you very much for that :smile:), but while testing whether I could now just avoid using `_raw` fields and get all fields manually I noticed there's still a missing field, which is `markDefs`.

In the screenshot below you can see I managed to grab all fields that I needed to make `body` the same as `_rawBody`, except for `markDefs`.

![printScreen](https://user-images.githubusercontent.com/390867/79334504-50d06a00-7f18-11ea-9091-8498e3fd3b56.PNG)

**Comment by kmelve** [comment]
Thanks for testing!

The case of the missing `markDefs` falls outside of the scope of what this fixes. To get this to work we need to make sure that Portable Text is fully typed, something we do plan to fix for upcoming iterations of the Portable Text specification and editor. 

I'll keep this issue open until that is in place.

**Comment by fvieira** [comment]
Oh, ok, I think I get it! `_raw` fields it is until then! :smile:

**Comment by bradley** [comment]
So does this mean we cant reliably use any marks/annotations in block content with sanity if we want to use graphql? This seems like a fairly big issue.

**Comment by Twoy519** [comment]
Sorry do I understand this issue correctly that if we are using graphql trying to render Portable Text, we're unable to do that as we won't have the ability to retrieve `markDefs`? I'm trying to simply render a BlockContent component using block-content-to-react and I think its breaking due to the inability to find the markDefs?

Hitting this:
```
TypeError: Cannot read property `find` of undefined in node_modules/@sanity/block-content-to-hyperscript/lib/buildMarksTree.js:52
```

From a page that looks like this:
```
import { graphql } from 'gatsby';
import React from 'react';
import BlockContent from '@sanity/block-content-to-react';
const serializers = {
  types: {
    block: (props) => BlockContent.defaultSerializers.types.block(props),
  },
};
export default function TestPage({ data }) {
  const { portableTextDescription } = data.item;
  console.log(portableTextDescription);
  return (
    <div>
      <BlockContent
        blocks={portableTextDescription}
        serializers={serializers}
      />
    </div>
  );
}
export const query = graphql`
  query TestItem {
    item: sanityItem(
      slug: { current: { eq: "slug-for-my-desired-product" } }
    ) {
      portableTextDescription {
        _key
        _type
        children {
          _key
          _type
          marks
          text
          __typename
        }
        style
        list
        _rawChildren
        __typename
      }
    }
  }
`;
```

**Comment by Twoy519** [comment]
So yeah when I manually appended `markDefs` to the graphql response, this fixed the error and it rendered correctly?

```
portableTextDescription.map((i) => {
  i.markDefs = [];
  return i;
});
```

**Comment by xyng** [comment]
I may be a little late to the party but wanted to note a possible solution for others finding this issue.
If you do not want to resort to using the `_raw...` field, you can add the markDefs field through `createResolvers` like so:

```typescript
export const createResolvers: GatsbyNode["createResolvers"] = ({ createResolvers }) => {
    createResolvers({
        SanityBlock: {
            markDefs: {
                type: "JSON",
                resolve: (source: any) => {
                    return source?.markDefs ?? null;
                }
            },
        }
    })
}
```

You could even narrow down the type for markDefs if you wanted, so selections of fields via GraphQL become possible. I've found `JSON` to be fair enough, as you probably need all fields anyways.

Are there any downsides going this route?
