### ISSUE TITLE
Copy Images in Gatsby build

### ISSUE THREAD

**Issue by marconucara** [sanity-io/gatsby-source-sanity#72]
Is it possibile to copy images in gatsby build instead of sourcing them from sanity dataset endpoint?
I can't find any options, maybe some workaround?

**Comment by kmelve** [comment]
You may be able to use this plugin: https://www.gatsbyjs.org/packages/gatsby-source-sanity-transform-images/?=sanity

For future questions, please join our [community](https://slack.sanity.io) and post in either the #help or #gatsby channels there. Thanks!
