### ISSUE TITLE
Deleted document keep showing up in gql

### ISSUE THREAD

**Issue by ahmedghazi** [sanity-io/gatsby-source-sanity#75]
Hello,

i have a weird pblm, i deleted some sample documents, then re started gatsby, and those deleted documents keep showing up > Zombie docs.
Is there a way to filter them? ex: status: "published"?
They don't show up in sanity studio though.

**Comment by kenjonespizza** [comment]
Hi @ahmedghazi ,

I bet you could delete them with the Sanity CLI.  It's pretty easy so long as you have the documents `id`.   Make sure it's the Sanity assigned id `_id`, and not the Gatsby assigned `id`

The command you're looking for is:
```sanity documents delete myDocId```
^ You can even add multiple id's to delete more than one at a time.

[https://www.sanity.io/docs/documents](https://www.sanity.io/docs/documents)

**Comment by bjoerge** [comment]
This should be fixed as of today's release of v7.0.0. Feel free to create a new issue if it still happens.
