### ISSUE TITLE
Typescript types not found using default module export

### ISSUE THREAD

**Issue by mshick** [sanity-io/gatsby-source-sanity#78]
I'm surprised I haven't seen this mentioned anywhere, so maybe I'm missing something, but the TypeScript compiler is unable to find this module's type defs when importing as usual, e.g.:

```
import {getFluidGatsbyImage} from 'gatsby-source-sanity'
```

Adding a `types` property to `package.json` should solve the problem:

```
{
  ...
  "types": "lib-es5/index.d.ts"
}
```

I've been able to import `gatsby-source-sanity/lib` in my project which also solves the issue, but that doesn't seem like a great solution.

**Comment by rexxars** [comment]
Thanks for reporting! Would you mind opening a pull request? We love community contributions! :)

**Comment by mshick** [comment]
Sure thing, just opened.
