### ISSUE TITLE
Gatsby not watching sanity for new published changes

### ISSUE THREAD

**Issue by nerdi-caveman** [sanity-io/gatsby-source-sanity#97]
I have a Gatsby site deployed to netlify. In development mode I set the option `watchMode:true` of `gatsby-source-sanity` in `gatsby-config.js` and this works fine to watch sanity studio for changes but in production it does not. I have tried adding a token and toggling the `watchMode` between `true` and `false`. The only way I see changes in production is to re build my site on Netlify. Is there something I am missing?

**Comment by Asjas** [comment]
I don't think `watchMode` is meant for Production hosted usage - you'll want to rebuild the site on Netlify after some time elapsed or after a change was made. 🙂 

There is even an error that is thrown when you try to use `watchMode` in a production build.
https://github.com/sanity-io/gatsby-source-sanity/blob/main/src/gatsby-node.ts#L300

**Comment by rexxars** [comment]
@Asjas is correct here :)

**Comment by nerdi-caveman** [comment]
@Asjas thank you. My problem was getting the site to auto build after each change. Configuring a webhook to sanity helped solve my problem. Also taking out watch more removed the error. Thanks 😊
