### ISSUE TITLE
[warning] Missing document

### ISSUE THREAD

**Issue by AnassZaki** [sanity-io/gatsby-source-sanity#98]
### Description
When running develop or build, I get this warning in the console:
```
warning [sanity] Document <document_name> has type <document_type> (Sanity<document_name>),
which is not declared in the GraphQL schema.
Make sure you run "graphql deploy". Skipping document.
```
Although I've removed all traces of these documents and deployed graphql in all my datasets using this command:
`sanity graphql deploy --dataset production --no-playground --force`

**Comment by sebbrown** [comment]
@AnassZaki did you find a solution to this issue? I’m also getting this message after removing a document type from the schema. 6 warnings appear which I believe correspond to the 6 documents that existed before the document type was deleted.

**Comment by AnassZaki** [comment]
@sebbrown Not yet...

**Comment by sebbrown** [comment]
@AnassZaki I found a solution for my instance, not sure if its applicable for you but all I needed to do was delete the old documents that existed in the dataset using their id as a reference. You can see all available methods for deleting the old documents here https://stackoverflow.com/questions/58837375/old-records-still-showing-on-sanity

**Comment by AnassZaki** [comment]
@sebbrown It actually worked!

### Solution
```
sanity documents delete <document_name>
```
